apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.serviceName }}
spec:
  ports:
  - port: {{ .Values.app.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.app.serviceTargetPort }}
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP