apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
spec:
  ports:
  - port: {{ .Values.db.servicePort }}
    targetPort: {{ .Values.db.serviceTargetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.db.name }}
  type: ClusterIP